#!/bin/sh
# Publish exported park data as a data-only PR without touching the working
# tree: a fresh worktree on origin/main receives each park's app files from
# data/export, a new cross-park species index and park index are written
# beside them, and the branch goes up with auto-merge. The batch chain calls
# this after every group of parks; it is safe to run by hand too.
#
#   scripts/publish_data.sh "title" park1 park2 ...
#
# sightings.parquet stays in data/export: the app never reads it and it was
# the largest file in every park folder (E-051).
set -eu
ROOT=$(cd "$(dirname "$0")/.." && pwd)
TITLE=$1; shift
PY=$ROOT/.venv/bin/python
BRANCH="data/$(date +%Y%m%d-%H%M%S)"
W=$ROOT/../parkwild-publish-$(date +%s)
git -C "$ROOT" fetch -q origin
git -C "$ROOT" worktree add -q -b "$BRANCH" "$W" origin/main
cleanup() { cd "$ROOT"; git worktree remove --force "$W" 2>/dev/null || true; git branch -q -D "$BRANCH" 2>/dev/null || true; }
trap cleanup EXIT
PARKS=""
for p in "$@"; do
  if [ ! -f "$ROOT/data/export/$p/manifest.json" ] || [ ! -f "$ROOT/data/export/$p/species.json" ]; then echo "publish: no export for $p; skipped" >&2; continue; fi
  mkdir -p "$W/app/public/data/$p"
  cp "$ROOT"/data/export/"$p"/*.geojson "$ROOT"/data/export/"$p"/*.json "$W/app/public/data/$p/"
  rm -f "$W/app/public/data/$p/sightings.parquet"
  PARKS="$PARKS $p"
done
[ -n "$PARKS" ] || { echo "publish: nothing to publish"; exit 0; }
$PY "$ROOT/scripts/track_a.py" species-index --data-dir "$W/app/public/data" --out "$W/app/public/data/species_index.json" >/dev/null
$PY "$ROOT/scripts/track_a.py" index --out "$W/app/public/data/parks.json" >/dev/null
BODY=$(mktemp)
{
  echo "Data only, no code. Parks in this drop, as each park's species file counts them:"; echo
  for p in $PARKS; do
    $PY -c "import json,sys; j=json.load(open(sys.argv[1])); print('- %s: %d species, %s sightings' % (j['park'], len(j['species']), format(sum(s['sightings'] for s in j['species']), ',')))" "$W/app/public/data/$p/species.json"
  done
  echo; echo "Generated by scripts/parks_batch.sh and scripts/publish_data.sh; the chain is recorded in EXPERIMENTS.md (E-051)."
  echo; echo "🤖 Generated with [Claude Code](https://claude.com/claude-code)"; echo; echo "https://claude.ai/code/session_01LPeDA3cg1C8wfiJ5cX2mAQ"
} > "$BODY"
cd "$W"
git add app/public/data
if git diff --cached --quiet; then echo "publish: nothing changed"; exit 0; fi
{ echo "$TITLE"; echo; sed -n '1,30p' "$BODY" | grep -v "Generated with\|claude.ai"; echo; echo "Co-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>"; echo "Claude-Session: https://claude.ai/code/session_01LPeDA3cg1C8wfiJ5cX2mAQ"; } | git commit -q -F -
git push -q -u origin "$BRANCH"
gh pr create --title "$TITLE" --body-file "$BODY" --base main --head "$BRANCH"
gh pr merge "$BRANCH" --auto --rebase >/dev/null
echo "publish: PR opened for $BRANCH ($PARKS )"
